<script setup>
import {computed,reactive,ref,onMounted} from 'vue'
import {useRouter} from 'vue-router'
import {getMyMember,updateMyMember,maskedPhone,memberProfileUrl} from '../../../services/myMemberApi'
import {errorMessage} from '../../../api/clients'
import {profileImage} from '../../../utils/profileImage'
import {auth} from '../../../stores/auth'
import '../../admin/members/members.css'
const router=useRouter(),member=ref(null),loading=ref(true),busy=ref(false),message=ref(''),errors=ref({}),failed=ref(false),form=reactive({name:'',email:''})
const phone=computed(()=>maskedPhone(member.value?.phone)),image=computed(()=>!failed.value&&memberProfileUrl(member.value?.profileImageUrl)||profileImage(member.value?.role))
function apply(data){member.value=data;form.name=data.name||'';form.email=data.email||'';failed.value=false}
onMounted(async()=>{try{apply(await getMyMember())}catch(e){message.value=errorMessage(e)}finally{loading.value=false}})
async function save(){if(busy.value)return;const e={};if(!form.name.trim())e.name='이름을 입력해 주세요.';else if(form.name.trim().length>30)e.name='이름은 30자 이내로 입력해 주세요.';if(form.email.trim()&&(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email.trim())||form.email.trim().length>100))e.email='올바른 이메일 주소를 입력해 주세요.';if(member.value.email&&!form.email.trim())e.email='이메일을 입력해 주세요.';errors.value=e;if(Object.keys(e).length)return;busy.value=true;message.value='';try{apply(await updateMyMember(form.name,form.email,member.value.email));if(auth.state.user)auth.state.user.name=member.value.name;message.value='회원정보가 저장되었습니다.'}catch(e){message.value=errorMessage(e)}finally{busy.value=false}}
</script>
<template><section class="members-page citizen-member-page"><header class="members-heading"><h1>회원정보</h1><p>내 회원 정보를 조회하고 수정할 수 있습니다.</p></header><p v-if="loading" role="status">불러오는 중입니다.</p><template v-else-if="member"><section class="member-summary" aria-label="내 회원정보"><div class="member-photo-wrap"><img class="member-photo" :src="image" :alt="member.name+' 프로필'" @error="failed=true"/></div><dl class="member-facts"><div><dt>이름</dt><dd>{{member.name}}</dd></div><div><dt>아이디</dt><dd>{{member.loginId}}</dd></div><div><dt>이메일</dt><dd>{{member.email || '미등록'}}</dd></div><div><dt>연락처</dt><dd>{{phone || '미등록'}}</dd></div></dl></section><section class="member-edit-card"><div class="member-tab-line"><h2>개인 정보</h2></div><form novalidate @submit.prevent="save"><div class="member-form-columns citizen-fields"><div class="member-form-column"><div class="member-field"><label for="citizen-name">이름 <span>*</span></label><input id="citizen-name" v-model="form.name" autocomplete="name" :aria-invalid="!!errors.name"/><p v-if="errors.name" class="member-error">{{errors.name}}</p></div><div class="member-field"><label for="citizen-email">이메일</label><div class="member-input-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/></svg><input id="citizen-email" v-model="form.email" type="email" autocomplete="email" :aria-invalid="!!errors.email"/></div><p v-if="errors.email" class="member-error">{{errors.email}}</p></div><div class="member-field"><label for="citizen-phone">연락처</label><div class="member-input-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 3H3c-1 10 8 19 18 18v-4l-5-2-2 2c-3-1-6-4-7-7l2-2Z"/></svg><input id="citizen-phone" :value="phone" readonly aria-readonly="true" placeholder="미등록"/></div></div></div></div><div class="member-actions"><button type="button" class="member-cancel" :disabled="busy" @click="router.push('/complaints')">취소</button><button type="submit" class="member-save" :disabled="busy">{{busy?'저장 중…':'저장하기'}}</button></div><p v-if="message" class="member-message" role="status">{{message}}</p></form></section></template><p v-else role="alert">{{message}}</p></section></template>

<style scoped>.citizen-fields { grid-template-columns:minmax(0,1fr); }</style>

