<script setup>
import {computed,reactive,ref,onMounted} from 'vue'
import {useRouter,useRoute} from 'vue-router'
import {vehicleStatuses,dispatchStatuses} from '../../mocks/fleet'
import {registrationOptions,registerFleet} from '../../services/fleetRegistration'
import {errorMessage} from '../../api/clients'
import {loadFleetRecord,updateFleetRecord} from '../../services/fleetManagement'
import train from '../../assets/train.png'
import {moveTypes} from '../../mocks/depotTimetable.js'
const props=defineProps({kind:{type:String,required:true}}),router=useRouter(),route=useRoute()
const editing=computed(()=>!!route.params.id)
const vehicle=computed(()=>props.kind==='vehicles'),title=computed(()=>(vehicle.value?'차량':'배차')+(editing.value?' 수정':' 등록'))
const form=reactive({vehicleNo:'',status:'STANDBY',lastInspectionDate:'',dispatchDate:'',moveType:'',trainNo:'',vehicleId:'',driverName:'',departureTime:'',arrivalTime:'',remark:''})
const options=ref({vehicles:[],drivers:[]}),errors=ref({}),message=ref(''),busy=ref(false),loading=ref(false)
const today=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
async function loadOptions(){loading.value=true;message.value='';try{options.value=await registrationOptions()}catch(e){message.value=errorMessage(e)}finally{loading.value=false}}
onMounted(async()=>{if(!vehicle.value)await loadOptions();if(editing.value){loading.value=true;try{const r=await loadFleetRecord(props.kind,route.params.id);for(const key of Object.keys(form))form[key]=r[key]??''}catch(e){message.value=errorMessage(e)}finally{loading.value=false}}})
async function submit(){if(busy.value)return;const e={};if(vehicle.value){if(!form.vehicleNo.trim())e.vehicleNo='차량번호를 입력해 주세요.';if(form.vehicleNo.trim().length>30)e.vehicleNo='30자 이내로 입력해 주세요.';if(!form.status)e.status='상태를 선택해 주세요.';if(form.lastInspectionDate>today())e.lastInspectionDate='점검일은 오늘 이후로 입력할 수 없습니다.'}else{const depot=!!form.moveType;for(const key of ['dispatchDate','vehicleId','driverName','departureTime',...(depot?['trainNo']:['arrivalTime'])])if(!String(form[key]).trim())e[key]='필수 항목입니다.';if(depot&&form.trainNo.trim()&&!/^[0-9A-Za-z-]{1,10}$/.test(form.trainNo.trim()))e.trainNo='열번은 숫자·영문 10자 이내로 입력해 주세요.';if(!depot&&form.arrivalTime&&form.departureTime&&form.arrivalTime<=form.departureTime)e.arrivalTime='도착시간은 출발시간보다 늦어야 합니다.';if(form.driverName.trim().length>30)e.driverName='30자 이내로 입력해 주세요.';if(form.remark.length>200)e.remark='200자 이내로 입력해 주세요.'}errors.value=e;if(Object.keys(e).length)return;busy.value=true;message.value='';try{if(editing.value)await updateFleetRecord(props.kind,route.params.id,form);else await registerFleet(props.kind,form);await router.push({path:'/dashboard/'+props.kind,query:{registered:'1'}})}catch(e){message.value=errorMessage(e)}finally{busy.value=false}}
const fields=computed(()=>vehicle.value?[{key:'vehicleNo',label:'차량번호',type:'text',max:30},{key:'status',label:'상태',type:'status'},{key:'lastInspectionDate',label:'최근 점검일',type:'date',optional:true},{key:'remark',label:'비고',type:'text',optional:true,unsupported:true}]:[{key:'dispatchDate',label:'배차일자',type:'date'},{key:'moveType',label:'구분',type:'move',optional:true},...(form.moveType?[{key:'trainNo',label:'열번',type:'text',max:10,unsupported:editing.value}]:[]),{key:'vehicleId',label:'차량',type:'vehicle'},{key:'driverName',label:'운전자명',type:'text',max:30},{key:'departureTime',label:form.moveType?(form.moveType==='DEPART'?'출고 시각':'입고 시각'):'출발시간',type:'time'},...(form.moveType?[]:[{key:'arrivalTime',label:'도착시간',type:'time'}]),{key:'remark',label:'비고',type:'text',max:200,optional:true},...(editing.value?[{key:'status',label:'상태',type:'status'}]:[])])
</script>
<template><section class="registration-page"><header><h1>{{title}}</h1><p>{{vehicle?'새 차량의 기본 정보를 입력해 주세요.':'차량과 운전자를 선택하고 운행 일정을 입력해 주세요. 입·출고 배차는 구분과 열번, 시각 하나만 입력합니다.'}}</p></header><section class="registration-card"><div class="registration-intro"><img :src="train" alt=""/><div><h2>{{vehicle?'차량 정보':'배차 정보'}}</h2><p>{{vehicle?'필수 항목을 입력한 후 등록해 주세요.':'배차번호는 자동 생성되며 배차 대기 상태로 등록됩니다.'}}</p></div></div><p v-if="message" role="alert" class="error">{{message}}</p><p v-if="loading" role="status">차량 선택 목록을 불러오는 중입니다.</p><button v-if="!vehicle&&message&&!options.vehicles.length" type="button" @click="loadOptions">선택 목록 다시 불러오기</button><form novalidate @submit.prevent="submit"><div class="registration-grid"><div v-for="field in fields" :key="field.key" class="field"><label :for="'register-'+field.key">{{field.label}} <span v-if="!field.optional">*</span></label><select v-if="field.type==='status'" :id="'register-'+field.key" v-model="form[field.key]"><option v-for="s in (vehicle?vehicleStatuses:dispatchStatuses)" :key="s.value" :value="s.value">{{s.label}}</option></select><select v-else-if="field.type==='move'" :id="'register-'+field.key" v-model="form[field.key]" :disabled="editing"><option value="">일반 운행 (출발~도착)</option><option v-for="m in moveTypes" :key="m.value" :value="m.value">{{m.label}} (입·출고 시간표)</option></select><select v-else-if="field.type==='vehicle'" :id="'register-'+field.key" v-model="form[field.key]" :disabled="loading"><option value="">차량을 선택해 주세요</option><option v-for="v in options.vehicles" :key="v.id" :value="v.id">{{v.vehicleNo}}</option></select><input v-else :disabled="field.unsupported" :placeholder="field.unsupported?'백엔드 비고 저장 필드가 필요합니다':undefined" :id="'register-'+field.key" v-model="form[field.key]" :type="field.type" :maxlength="field.max" :max="vehicle&&field.type==='date'?today():undefined" :list="field.key==='driverName'?'driver-options':undefined" :aria-invalid="!!errors[field.key]" :aria-describedby="errors[field.key]?'error-'+field.key:undefined"/><p v-if="errors[field.key]" :id="'error-'+field.key" class="error">{{errors[field.key]}}</p></div></div><datalist id="driver-options"><option v-for="d in options.drivers" :key="d" :value="d"/></datalist><footer><button type="button" class="secondary" :disabled="busy" @click="router.push('/dashboard/'+kind)">취소</button><button type="submit" class="primary" :disabled="busy||loading">{{busy?'저장 중…':editing?'저장하기':'등록하기'}}</button></footer></form></section></section></template>
<style scoped>
.registration-page{color:#344d60;max-width:1400px;margin:0 auto}.registration-page h1{margin:0;color:#064b76;font-size:40px;font-weight:800}.registration-page header p{margin:10px 0 24px;font-size:17px;color:#7c8b98}.registration-card{border:1px solid #dce8ef;border-radius:18px;padding:28px;background:white}.registration-intro{display:flex;align-items:center;gap:22px;padding-bottom:24px;margin-bottom:24px;border-bottom:1px solid #e5edf3}.registration-intro img{width:110px;height:65px;object-fit:contain}.registration-intro h2{margin:0 0 8px;font-size:23px;color:#064b76}.registration-intro p{margin:0;font-size:16px}.registration-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:22px 32px}.field{min-width:0}.field label{display:block;margin-bottom:8px;font-size:17px;font-weight:700;color:#173e5c}.field label span,.error{color:#bc4141}.field input,.field select{box-sizing:border-box;width:100%;height:48px;border:1px solid #c9dce8;border-radius:10px;padding:0 14px;font:inherit;background:white;color:#344d60}.error{margin:7px 0;font-size:14px}footer{display:flex;justify-content:flex-end;gap:12px;margin-top:28px}footer button{height:48px;padding:0 28px;border-radius:10px;font:inherit;font-weight:700;cursor:pointer}.secondary{background:white;border:1px solid #adcddd;color:#065782}.primary{background:#065782;border:1px solid #065782;color:white}.primary:hover{background:#034b72}button:disabled{opacity:.55;cursor:not-allowed}.registration-page :is(input,select,button):focus-visible{outline:3px solid #64b3e0;outline-offset:2px}@media(max-height:800px){.registration-card{padding:22px}.registration-intro{padding-bottom:16px;margin-bottom:18px}.registration-grid{gap:16px 26px}footer{margin-top:22px}}@media(max-width:700px){.registration-grid{grid-template-columns:1fr}.registration-card{padding:18px}.registration-intro{gap:12px}.registration-intro img{width:75px}.registration-page h1{font-size:32px}}
</style>
