<script setup>
import { ref } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import train from '../../assets/train.png'
import NumberPagination from '../common/NumberPagination.vue'
import { useFleetList } from '../../composables/useFleetList'
import {rememberFleetPreview} from '../../services/fleetDetailPreview'
import { fleetDestination } from '../../services/mockFleet'
import { errorMessage } from '../../api/clients'
import { moveTypes, depotTimetable } from '../../mocks/depotTimetable.js'
const props=defineProps({kind:{type:String,required:true}})
const vehicle=props.kind==='vehicles'
const {appliedStatus,source,draft,page,rows,summary,depotCounts,dayInfo,totalPages,pages,selected,allSelected,search,move,selectAll,generate,error}=useFleetList(props.kind)
const router=useRouter(),route=useRoute()
const notice=ref(route.query.registered==='1'?'등록되었습니다.':'')
function open(action,id){if(action==='create'){router.push('/dashboard/'+props.kind+'/new');return}if(action==='detail'){const selectedRow=rows.value.find(row=>String(row.id)===String(id));if(selectedRow)rememberFleetPreview(props.kind,selectedRow);router.push({name:vehicle?'admin-vehicle-detail':'admin-dispatch-detail',params:{id}});return}const target=fleetDestination(props.kind,action,id);notice.value=target.message+(target.id?' · '+(vehicle?'차량':'배차')+' ID: '+target.id:'')}
function filterByCard(card){draft.status=card.status;search()}
const status=c=>source.statuses.find(o=>o.value===c.status)
const date=v=>v?.replaceAll('-','.')||'—'
// 입·출고 배차는 시각이 하나(출고/입고 시각), 일반 배차는 출발~도착
const timeText=c=>c.moveType?c.departureTime.slice(0,5):c.departureTime.slice(0,5)+'~'+c.arrivalTime.slice(0,5)
const moveTone=c=>moveTypes.find(o=>o.value===c.moveType)?.tone
// 선택한 날짜의 입·출고 시간표로 배차 만들기
const generating=ref(false),showTimetable=ref(false)
async function generateFromTimetable(){
 const target=dayInfo.value;if(!target||generating.value)return
 if(!window.confirm(date(target.date)+' ('+target.dayTypeLabel+') 입·출고 시간표로 배차를 만들까요?'))return
 generating.value=true
 try{const r=await generate(target.date);notice.value=date(r.date)+' '+r.dayTypeLabel+' 시간표로 배차 '+r.created+'건을 만들었습니다.'}
 catch(e){notice.value=errorMessage(e)}
 finally{generating.value=false}
}
const timetable=()=>dayInfo.value?depotTimetable[dayInfo.value.dayType]:null
</script>
<template><section class="fleet-list"><h1>{{vehicle?'차량관리':'배차관리'}}</h1><div v-if="!vehicle" class="depot-bar"><p v-if="dayInfo"><strong>{{date(dayInfo.date)}}</strong> · {{dayInfo.dayTypeLabel}} 입·출고 시간표 <span class="depot-count" data-tone="blue">출고 {{depotCounts?.departs??'—'}}건</span><span class="depot-count" data-tone="green">입고 {{depotCounts?.returns??'—'}}건</span></p><p v-else>날짜를 선택하면 그날의 평일·토요일·휴일 입·출고 시간표 기준으로 볼 수 있습니다.</p><div v-if="dayInfo" class="depot-actions"><button type="button" @click="showTimetable=!showTimetable" :aria-expanded="showTimetable">{{showTimetable?'시간표 닫기':'시간표 보기'}}</button><button type="button" :disabled="generating" @click="generateFromTimetable">{{generating?'만드는 중…':'시간표로 배차 만들기'}}</button></div></div><div v-if="!vehicle&&showTimetable&&timetable()" class="timetable-panel" aria-label="입·출고 시간표"><div v-for="part in [{key:'departs',label:'출고'},{key:'returns',label:'입고'}]" :key="part.key"><h2>{{dayInfo.dayTypeLabel}} {{part.label}} {{timetable()[part.key].length}}회</h2><ol><li v-for="([no,t],i) in timetable()[part.key]" :key="part.key+i"><b>{{no}}</b>{{t}}</li></ol></div></div><div class="fleet-summary"><button type="button" class="summary-filter" v-for="card in summary" :key="card.label" :data-tone="card.tone" :class="{active:appliedStatus===card.status}" :aria-pressed="appliedStatus===card.status" :aria-label="card.label+' 필터'" @click="filterByCard(card)"><span class="summary-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><rect x="5" y="3" width="14" height="16" rx="4"/><path d="M5 11h14M8 7h8m-8 8h1m6 0h1M8 19l-2 3m10-3 2 3"/></svg></span><div><p>{{card.label}}</p><strong>{{card.value}}<small>{{vehicle?'대':'건'}}</small></strong></div></button></div>
<form class="fleet-search" :class="{'dispatch-search':!vehicle}" @submit.prevent="search"><input class="keyword" v-model="draft.keyword" aria-label="검색어" :placeholder="vehicle?'차량번호 검색':'배차번호, 열번, 차량번호, 운전자명 검색'"/><template v-if="!vehicle"><input type="date" v-model="draft.date" aria-label="배차일자"/><button v-if="draft.date" class="clear-date" type="button" @click="draft.date=''">날짜 해제</button><select v-model="draft.moveType" aria-label="입·출고 구분"><option value="">전체 구분</option><option v-for="o in moveTypes" :key="o.value" :value="o.value">{{o.label}}</option></select><select v-model="draft.vehicleId" aria-label="차량"><option value="">전체 차량</option><option v-for="v in source.vehicles" :key="v.id" :value="v.id">{{v.vehicleNo}}</option></select><select v-model="draft.driver" aria-label="운전자"><option value="">전체 운전자</option><option v-for="d in source.drivers" :key="d.value" :value="d.value">{{d.label}}</option></select></template><select v-model="draft.status" aria-label="상태"><option value="">전체</option><option v-for="o in source.statuses" :key="o.value" :value="o.value">{{o.label}}</option></select><button class="primary" type="submit">검색</button><button class="register" type="button" @click="open('create')">+ {{vehicle?'차량':'배차'}} 등록</button></form>
<p v-if="error" role="alert">{{error}}</p><p v-if="notice" class="fleet-notice" role="status">{{notice}}</p>
<div class="fleet-table"><table :class="{'dispatch-table':!vehicle}"><colgroup v-if="vehicle"><col style="width:44px"/><col style="width:110px"/><col/><col style="width:180px"/><col style="width:180px"/><col style="width:130px"/></colgroup><colgroup v-else><col style="width:36px"/><col style="width:128px"/><col style="width:100px"/><col style="width:70px"/><col style="width:70px"/><col style="width:82px"/><col style="width:84px"/><col style="width:104px"/><col style="width:96px"/><col/><col style="width:104px"/></colgroup><thead><tr><th><input type="checkbox" aria-label="현재 페이지 전체 선택" :checked="allSelected" :indeterminate="selected.length>0&&!allSelected" @change="selectAll($event.target.checked)"/></th><template v-if="vehicle"><th>차량 이미지</th><th>차량번호</th><th>상태</th><th>최근 점검일</th></template><template v-else><th>배차번호</th><th>배차일자</th><th>구분</th><th>열번</th><th>차량번호</th><th>운전자명</th><th>시각</th><th>상태</th><th>비고</th></template><th>관리</th></tr></thead><tbody><tr v-for="c in rows" :key="c.id"><td><input type="checkbox" v-model="selected" :value="c.id" :aria-label="c.id+'번 선택'"/></td><template v-if="vehicle"><td><img :src="train" alt="차량 기본 이미지"/></td><td><button class="text-button" @click="open('detail',c.id)">{{c.vehicleNo}}</button></td><td><span class="fleet-badge" :data-tone="status(c)?.tone">{{status(c)?.label}}</span></td><td>{{date(c.lastInspectionDate)}}</td></template><template v-else><td><button class="text-button" @click="open('detail',c.id)">{{c.dispatchNo}}</button></td><td>{{date(c.dispatchDate)}}</td><td><span v-if="c.moveType" class="fleet-badge" :data-tone="moveTone(c)">{{c.moveTypeLabel}}</span><span v-else class="muted">일반</span></td><td>{{c.trainNo||'—'}}</td><td>{{c.vehicleNo}}</td><td>{{c.driverName}}</td><td>{{timeText(c)}}</td><td><span class="fleet-badge" :data-tone="status(c)?.tone">{{status(c)?.label}}</span></td><td class="remark"><span :title="c.remark">{{c.remark}}</span></td></template><td><button class="detail-button" @click="open('detail',c.id)"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></svg>상세보기</button></td></tr><tr v-if="!rows.length"><td :colspan="vehicle?6:11">검색 결과가 없습니다.<template v-if="!vehicle&&dayInfo"> 위의 「시간표로 배차 만들기」로 이 날짜의 입·출고 배차를 만들 수 있습니다.</template></td></tr></tbody></table></div>
<NumberPagination :page="page" :pages="pages" :total-pages="totalPages" @change="move"/></section></template>
<style scoped>
.summary-filter{font:inherit;text-align:left;color:inherit;cursor:pointer;box-sizing:border-box;min-width:0;transition:background-color 180ms ease-out,border-color 180ms ease-out,box-shadow 180ms ease-out}.fleet-summary .summary-filter:hover{background:#edf7fc;border-color:#a8cce0}.fleet-summary .summary-filter.active{background:#e9f5fc;border-color:#0879ac;box-shadow:inset 0 0 0 1px #0879ac}
.fleet-list{position:relative;height:100%;min-height:650px;display:flex;flex-direction:column;gap:16px;color:#354755}.fleet-list h1{margin:0;color:#064b76;font-size:40px;font-weight:800;line-height:1.3}.fleet-summary{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:16px}.fleet-summary .summary-filter{display:flex;align-items:center;gap:14px;padding:18px;border:1px solid #dceaf2;border-radius:12px;min-height:106px;background:#f9fcfe}.summary-icon{width:42px;height:42px;border-radius:50%;display:grid;place-items:center;background:#e6f4fc;color:#1c7eac;flex-shrink:0}.summary-icon svg{width:24px;fill:none;stroke:currentColor;stroke-width:1.6}.fleet-summary p{margin:0 0 6px;font-size:16px;font-weight:700}.fleet-summary strong{font-size:30px;color:#075a83}.fleet-summary small{font-size:15px;margin-left:7px;font-weight:500}.fleet-search{display:flex;flex-wrap:wrap;gap:10px;align-items:center}.fleet-search :is(input,select,button){height:42px;border:1px solid #c7dce8;border-radius:8px;padding:0 12px;font:inherit;font-size:15px;background:white;color:#344d60}.fleet-search .keyword{flex:1;min-width:240px}.fleet-search select{min-width:120px}.fleet-search .primary,.fleet-search .register{background:#065782;color:white;border-color:#065782;font-weight:700;white-space:nowrap;cursor:pointer}.fleet-search .register{background:#0875a8}.fleet-notice{position:absolute;right:0;top:12px;max-width:55%;margin:0;font-size:14px;min-height:20px;color:#075a83}.fleet-table{flex:1;min-height:0;overflow-x:auto;display:flex;flex-direction:column}.fleet-table table{width:100%;height:100%;border-collapse:collapse;table-layout:fixed;min-width:700px;font-size:15px}.fleet-table .dispatch-table{min-width:1100px}th{background:#f2f8fc;color:#31536c;font-size:15px;font-weight:700;height:40px}td{padding:4px 8px;border-bottom:1px solid #e5edf3;text-align:center;height:40px}tbody tr:hover{background:#f3faff}td img{display:block;margin:auto;width:60px;height:36px;object-fit:contain}.fleet-badge{display:inline-block;padding:4px 9px;border-radius:16px;font-size:14px;white-space:nowrap}.fleet-badge[data-tone=green]{color:#348452;background:#eaf8ef}.fleet-badge[data-tone=blue]{color:#3875b4;background:#edf4ff}.fleet-badge[data-tone=orange]{color:#ab6720;background:#fff4e7}.fleet-badge[data-tone=red]{color:#ba4646;background:#fff0ef}.text-button,.detail-button{padding:0;border:0;background:none;font:inherit;color:#126a95;cursor:pointer}.detail-button{display:inline-flex;gap:5px;align-items:center;white-space:nowrap;font-size:14px}.detail-button svg{width:18px;height:18px;fill:none;stroke:currentColor;stroke-width:1.6}.remark span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}input[type=checkbox]{width:16px;height:16px;accent-color:#0078ae}.fleet-list :is(button,input,select):focus-visible{outline:3px solid #64b3e0;outline-offset:2px}
@media(max-width:1500px){.dispatch-search .keyword{flex-basis:calc(100% - 230px)}.fleet-summary .summary-filter{padding:12px;gap:10px}.fleet-summary{gap:12px}}
@media(min-width:1101px) and (max-height:850px){.fleet-list{min-height:0;gap:10px}.fleet-list h1{font-size:34px}.fleet-summary .summary-filter{min-height:80px;padding:10px}.fleet-summary strong{font-size:26px}.fleet-summary p{font-size:15px}.fleet-table td{height:32px;padding:0 5px}.fleet-table th{height:34px}.fleet-table td img{height:32px}.fleet-notice{min-height:18px}}
@media(max-width:1100px){.fleet-list{position:relative;height:auto;min-height:0}.fleet-summary{grid-template-columns:repeat(2,minmax(0,1fr))}.fleet-table table{height:auto}.fleet-search .keyword{flex-basis:100%}.fleet-table{flex:none}}
/* 입·출고 시간표 안내줄 */
.depot-bar{display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;gap:10px;margin-top:-6px}.depot-bar p{margin:0;font-size:15px;color:#4d6577}.depot-bar strong{color:#064b76}.depot-count{display:inline-block;margin-left:8px;padding:3px 9px;border-radius:14px;font-size:14px;font-weight:700}.depot-count[data-tone=blue]{color:#3875b4;background:#edf4ff}.depot-count[data-tone=green]{color:#348452;background:#eaf8ef}.depot-actions{display:flex;gap:8px}.depot-actions button{height:36px;padding:0 14px;border:1px solid #adcddd;border-radius:8px;background:#fff;color:#065782;font:inherit;font-size:14px;font-weight:700;cursor:pointer}.depot-actions button:hover{background:#edf7fc}.depot-actions button:disabled{opacity:.55;cursor:not-allowed}
.timetable-panel{display:grid;grid-template-columns:1fr 1fr;gap:12px;padding:14px;border:1px solid #dceaf2;border-radius:12px;background:#f9fcfe}.timetable-panel h2{margin:0 0 8px;font-size:15px;color:#064b76}.timetable-panel ol{margin:0;padding:0;list-style:none;display:grid;grid-template-columns:repeat(auto-fill,minmax(92px,1fr));gap:4px 8px;max-height:150px;overflow:auto}.timetable-panel li{font-size:13px;color:#4d6577;white-space:nowrap}.timetable-panel b{display:inline-block;min-width:38px;margin-right:4px;color:#173e5c}
.muted{color:#93a3af;font-size:14px}
@media(max-width:1100px){.timetable-panel{grid-template-columns:1fr}}
</style>




