<script setup>
import { ref } from 'vue'
import train from '../../assets/train.png'
import NumberPagination from '../common/NumberPagination.vue'
import { useFleetList } from '../../composables/useFleetList'
import { fleetDestination } from '../../services/mockFleet'
const props=defineProps({kind:{type:String,required:true}})
const vehicle=props.kind==='vehicles'
const {source,draft,page,rows,summary,totalPages,pages,selected,allSelected,search,move,selectAll}=useFleetList(props.kind)
const notice=ref('')
function open(action,id){const target=fleetDestination(props.kind,action,id);notice.value=target.message+(target.id?' · '+(vehicle?'차량':'배차')+' ID: '+target.id:'')}
const status=c=>source.statuses.find(o=>o.value===c.status)
const date=v=>v.replaceAll('-','.')
</script>
<template><section class="fleet-list"><h1>{{vehicle?'차량관리':'배차관리'}}</h1><div class="fleet-summary"><article v-for="card in summary" :key="card.label" :data-tone="card.tone"><span class="summary-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><rect x="5" y="3" width="14" height="16" rx="4"/><path d="M5 11h14M8 7h8m-8 8h1m6 0h1M8 19l-2 3m10-3 2 3"/></svg></span><div><p>{{card.label}}</p><strong>{{card.value}}<small>{{vehicle?'대':'건'}}</small></strong></div></article></div>
<form class="fleet-search" :class="{'dispatch-search':!vehicle}" @submit.prevent="search"><input class="keyword" v-model="draft.keyword" aria-label="검색어" :placeholder="vehicle?'차량번호 검색':'배차번호, 차량번호, 운전자명 검색'"/><template v-if="!vehicle"><input type="date" v-model="draft.date" aria-label="배차일자"/><button v-if="draft.date" class="clear-date" type="button" @click="draft.date=''">날짜 해제</button><select v-model="draft.vehicleId" aria-label="차량"><option value="">전체 차량</option><option v-for="v in source.vehicles" :key="v.id" :value="v.id">{{v.vehicleNo}}</option></select><select v-model="draft.driver" aria-label="운전자"><option value="">전체 운전자</option><option v-for="d in source.drivers" :key="d.value" :value="d.value">{{d.label}}</option></select></template><select v-model="draft.status" aria-label="상태"><option value="">전체</option><option v-for="o in source.statuses" :key="o.value" :value="o.value">{{o.label}}</option></select><button class="primary" type="submit">검색</button><button class="register" type="button" @click="open('create')">+ {{vehicle?'차량':'배차'}} 등록</button></form>
<p v-if="notice" class="fleet-notice" role="status">{{notice}}</p>
<div class="fleet-table"><table :class="{'dispatch-table':!vehicle}"><colgroup v-if="vehicle"><col style="width:44px"/><col style="width:110px"/><col/><col style="width:180px"/><col style="width:180px"/><col style="width:130px"/></colgroup><colgroup v-else><col style="width:36px"/><col style="width:88px"/><col style="width:106px"/><col style="width:84px"/><col style="width:92px"/><col style="width:84px"/><col style="width:84px"/><col style="width:108px"/><col/><col style="width:108px"/></colgroup><thead><tr><th><input type="checkbox" aria-label="현재 페이지 전체 선택" :checked="allSelected" :indeterminate="selected.length>0&&!allSelected" @change="selectAll($event.target.checked)"/></th><template v-if="vehicle"><th>차량 이미지</th><th>차량번호</th><th>상태</th><th>최근 점검일</th></template><template v-else><th>배차번호</th><th>배차일자</th><th>차량번호</th><th>운전자명</th><th>출발시간</th><th>도착시간</th><th>상태</th><th>비고</th></template><th>관리</th></tr></thead><tbody><tr v-for="c in rows" :key="c.id"><td><input type="checkbox" v-model="selected" :value="c.id" :aria-label="c.id+'번 선택'"/></td><template v-if="vehicle"><td><img :src="train" alt="차량 기본 이미지"/></td><td><button class="text-button" @click="open('detail',c.id)">{{c.vehicleNo}}</button></td><td><span class="fleet-badge" :data-tone="status(c)?.tone">{{status(c)?.label}}</span></td><td>{{date(c.lastInspectionDate)}}</td></template><template v-else><td><button class="text-button" @click="open('detail',c.id)">{{c.dispatchNo}}</button></td><td>{{date(c.dispatchDate)}}</td><td>{{c.vehicleNo}}</td><td>{{c.driverName}}</td><td>{{c.departureTime.slice(0,5)}}</td><td>{{c.arrivalTime.slice(0,5)}}</td><td><span class="fleet-badge" :data-tone="status(c)?.tone">{{status(c)?.label}}</span></td><td class="remark"><span :title="c.remark">{{c.remark}}</span></td></template><td><button class="detail-button" @click="open('detail',c.id)"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></svg>상세보기</button></td></tr><tr v-if="!rows.length"><td :colspan="vehicle?6:10">검색 결과가 없습니다.</td></tr></tbody></table></div>
<NumberPagination :page="page" :pages="pages" :total-pages="totalPages" @change="move"/></section></template>
<style scoped>
.fleet-list{position:relative;height:100%;min-height:650px;display:flex;flex-direction:column;gap:16px;color:#354755}.fleet-list h1{margin:0;color:#064b76;font-size:40px;font-weight:900;line-height:1.3}.fleet-summary{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:16px}.fleet-summary article{display:flex;align-items:center;gap:14px;padding:18px;border:1px solid #dceaf2;border-radius:12px;min-height:106px;background:#f9fcfe}.summary-icon{width:42px;height:42px;border-radius:50%;display:grid;place-items:center;background:#e6f4fc;color:#1c7eac;flex-shrink:0}.summary-icon svg{width:24px;fill:none;stroke:currentColor;stroke-width:1.6}.fleet-summary p{margin:0 0 6px;font-size:16px;font-weight:700}.fleet-summary strong{font-size:30px;color:#075a83}.fleet-summary small{font-size:15px;margin-left:7px;font-weight:500}.fleet-search{display:flex;flex-wrap:wrap;gap:10px;align-items:center}.fleet-search :is(input,select,button){height:42px;border:1px solid #c7dce8;border-radius:8px;padding:0 12px;font:inherit;font-size:15px;background:white;color:#344d60}.fleet-search .keyword{flex:1;min-width:240px}.fleet-search select{min-width:120px}.fleet-search .primary,.fleet-search .register{background:#065782;color:white;border-color:#065782;font-weight:700;white-space:nowrap;cursor:pointer}.fleet-search .register{background:#0875a8}.fleet-notice{position:absolute;right:0;top:12px;max-width:55%;margin:0;font-size:14px;min-height:20px;color:#075a83}.fleet-table{flex:1;min-height:0;overflow-x:auto;display:flex;flex-direction:column}.fleet-table table{width:100%;height:100%;border-collapse:collapse;table-layout:fixed;min-width:700px;font-size:15px}.fleet-table .dispatch-table{min-width:980px}th{background:#f2f8fc;color:#31536c;font-size:15px;font-weight:700;height:40px}td{padding:4px 8px;border-bottom:1px solid #e5edf3;text-align:center;height:40px}tbody tr:hover{background:#f3faff}td img{display:block;margin:auto;width:60px;height:36px;object-fit:contain}.fleet-badge{display:inline-block;padding:4px 9px;border-radius:16px;font-size:14px;white-space:nowrap}.fleet-badge[data-tone=green]{color:#348452;background:#eaf8ef}.fleet-badge[data-tone=blue]{color:#3875b4;background:#edf4ff}.fleet-badge[data-tone=orange]{color:#ab6720;background:#fff4e7}.fleet-badge[data-tone=red]{color:#ba4646;background:#fff0ef}.text-button,.detail-button{padding:0;border:0;background:none;font:inherit;color:#126a95;cursor:pointer}.detail-button{display:inline-flex;gap:5px;align-items:center;white-space:nowrap;font-size:14px}.detail-button svg{width:18px;height:18px;fill:none;stroke:currentColor;stroke-width:1.6}.remark span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}input[type=checkbox]{width:16px;height:16px;accent-color:#0078ae}.fleet-list :is(button,input,select):focus-visible{outline:3px solid #64b3e0;outline-offset:2px}
@media(max-width:1500px){.dispatch-search .keyword{flex-basis:calc(100% - 230px)}.fleet-summary article{padding:12px;gap:10px}.fleet-summary{gap:12px}}
@media(min-width:1101px) and (max-height:850px){.fleet-list{min-height:0;gap:10px}.fleet-list h1{font-size:34px}.fleet-summary article{min-height:80px;padding:10px}.fleet-summary strong{font-size:26px}.fleet-summary p{font-size:15px}.fleet-table td{height:32px;padding:0 5px}.fleet-table th{height:34px}.fleet-table td img{height:32px}.fleet-notice{min-height:18px}}
@media(max-width:1100px){.fleet-list{position:relative;height:auto;min-height:0}.fleet-summary{grid-template-columns:repeat(2,minmax(0,1fr))}.fleet-table table{height:auto}.fleet-search .keyword{flex-basis:100%}.fleet-table{flex:none}}
</style>


