import {reactive,ref,computed,watch} from 'vue'
import {general,errorMessage} from '../api/clients'
import {getFleetSource} from '../services/mockFleet'
export function useLiveFleet(kind){const initial=getFleetSource(kind),source=reactive({statuses:initial.statuses,vehicles:[],drivers:[]}),draft=reactive({keyword:'',date:'',vehicleId:'',driver:'',status:''}),applied=reactive({...draft}),page=ref(1),rows=ref([]),counts=ref(null),totalPages=ref(1),selected=ref([]),error=ref('');let sequence=0
async function load(){const request=++sequence;const filters=Object.fromEntries(Object.entries(applied).filter(([,v])=>v!==''));const summaryFilters=kind==='vehicles'?{}:Object.fromEntries(Object.entries(filters).filter(([k])=>k!=='status'));try{const [list,summary]=await Promise.all([general('get','/api/v1/admin/'+kind,undefined,{...filters,page:page.value-1,size:10}),general('get','/api/v1/admin/'+kind+'/summary',undefined,summaryFilters)]);if(request!==sequence)return;rows.value=list.content;counts.value=summary;totalPages.value=Math.max(1,list.totalPages);error.value=''}catch(e){if(request===sequence)error.value=errorMessage(e)}}
if(kind==='dispatches')general('get','/api/v1/admin/dispatches/options').then(o=>{source.vehicles=o.vehicles;source.drivers=o.drivers.map(d=>({value:d,label:d}))}).catch(e=>error.value=errorMessage(e))
watch(()=>[page.value,JSON.stringify(applied)],load,{immediate:true})
const keys={RUNNING:'running',STANDBY:'standby',MAINTENANCE:'maintenance',STOPPED:'stopped',COMPLETED:'completed',WAITING:'waiting',CHANGED:'changed',CANCELLED:'cancelled'}
const summary=computed(()=>[{label:kind==='vehicles'?'전체 차량':'전체 배차',value:counts.value?.total??'—',tone:'all',status:''},...source.statuses.map(o=>({...o,status:o.value,value:counts.value?.[keys[o.value]]??'—'}))]),requestPage=computed(()=>page.value-1),pages=computed(()=>{const start=Math.floor((page.value-1)/5)*5+1;return Array.from({length:Math.min(5,totalPages.value-start+1)},(_,i)=>start+i)}),allSelected=computed(()=>rows.value.length>0&&rows.value.every(r=>selected.value.includes(r.id)))
function search(){Object.assign(applied,{...draft,keyword:draft.keyword.trim()});if(page.value===1)load();else page.value=1;selected.value=[]}function move(p){page.value=Math.max(1,Math.min(totalPages.value,p));selected.value=[]}function selectAll(v){selected.value=v?rows.value.map(r=>r.id):[]}
return {appliedStatus:computed(()=>applied.status),source,draft,page,rows,summary,totalPages,pages,selected,allSelected,search,move,selectAll,error,requestPage,size:10}}
