<script setup>
import {reactive,ref,watch,computed} from 'vue'
import {useRouter} from 'vue-router'
import '../../../styles/complaint-detail.css'
import {useComplaintDetail} from '../../../composables/useComplaintDetail'
import {complaintOptions,updateComplaint} from '../../../services/complaintApi'
import {currentUser} from '../../../stores/currentUser'
import {errorMessage} from '../../../api/clients'
const {complaint,loading,error}=useComplaintDetail(),router=useRouter(),draft=reactive({type:'',category:'',title:'',content:''}),options=ref({types:[],categories:[]}),files=ref([]),deleted=ref([]),busy=ref(false),message=ref('')
const editable=computed(()=>complaint.value?.editable&&complaint.value.status==='WAITING'&&currentUser.value?.loginId!=='admin'&&String(currentUser.value?.id)===String(complaint.value.writerId))
watch(complaint,c=>{if(c){for(const key of Object.keys(draft))draft[key]=c[key];files.value=[];deleted.value=[]}})
complaintOptions().then(o=>options.value=o).catch(e=>message.value=errorMessage(e))
function choose(e){files.value.push(...Array.from(e.target.files));e.target.value=''}
async function save(){if(busy.value||!editable.value)return;message.value='';if(!draft.type||!draft.category||!draft.title.trim()||!draft.content.trim()){message.value='민원유형, 분류, 제목, 내용을 입력해 주세요.';return}if(draft.title.length>200||draft.content.length>5000){message.value='제목은 200자, 내용은 5,000자 이내로 입력해 주세요.';return}busy.value=true;try{await updateComplaint(complaint.value.id,draft,files.value,deleted.value);await router.replace('/complaints/'+complaint.value.id)}catch(e){message.value=errorMessage(e)}finally{busy.value=false}}
</script>
<template><section class="complaint-detail"><header class="complaint-detail-heading"><div><RouterLink class="complaint-back" :to="'/complaints/'+complaint?.id">← 민원 상세</RouterLink><h2>민원 수정</h2><p>등록한 민원의 내용을 수정할 수 있습니다.</p></div></header><p v-if="loading">불러오는 중입니다.</p><form v-else-if="editable" class="complaint-card" @submit.prevent="save"><div class="complaint-edit-fields"><label>민원유형<select v-model="draft.type" required><option v-for="o in options.types" :key="o.code" :value="o.code">{{o.label}}</option></select></label><label>분류<select v-model="draft.category" required><option v-for="o in options.categories" :key="o.code" :value="o.code">{{o.label}}</option></select></label><label class="full">제목<input v-model="draft.title" required maxlength="200"/></label><label class="full">내용<textarea v-model="draft.content" required maxlength="5000"/></label><section class="full"><h3>기존 첨부파일</h3><label v-for="file in complaint.attachments" :key="file.id"><span><input style="width:auto" type="checkbox" v-model="deleted" :value="file.id"/> 삭제 · {{file.originalFileName}}</span></label><p v-if="!complaint.attachments.length">첨부파일이 없습니다.</p></section><label class="full">첨부파일 추가<input type="file" accept="image/*,application/pdf" multiple @change="choose"/></label><ul class="full"><li v-for="(file,i) in files" :key="i">{{file.name}} <button type="button" @click="files.splice(i,1)">제거</button></li></ul></div><p v-if="message" class="complaint-error" role="alert">{{message}}</p><div class="complaint-actions"><RouterLink class="secondary" :to="'/complaints/'+complaint.id">취소</RouterLink><button :disabled="busy">{{busy?'저장 중…':'수정 완료'}}</button></div></form><p v-else>{{error||'접수대기 상태의 본인 민원만 수정할 수 있습니다.'}}</p></section></template>
